### ISSUE TITLE
Ng Add Fails

### ISSUE THREAD

**Issue by AArhin** [NarikMe/narik-angular#36]
Hi,
     Just stumbled on your project and decided to give it a try after going through the impressive live demos.
Now doing ng Add list narik@1.0.0 instead of narik@7.0.0 which eventually fails.
This is my development environment:

Angular CLI : 13.1.2
Node: 16.13.1
npm : 8.1.2
OS :Win32 x64

Thanks

**Comment by abadakhshan** [comment]
Thank you  @AArhin  reporting this issue.
The main cause of this issue was https://github.com/angular/angular-cli/issues/17983

I fixed it.

If you use npm 8 you should use --force for installing dependencies but I suggest that you use yarn when you create the Angular project with this command

`ng new --package-manager yarn`
